name: abrabar
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter_svg: ^1.1.0
  sizer: ^2.0.15
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  bloc: ^8.0.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.2

flutter_native_splash:
  background_image: assets/images/splash.png   

flutter:
  generate: true
  assets:
        - assets/
        - assets/images/
        - assets/images/parts/
        - assets/images/test/
  uses-material-design: true
  fonts: 
    - family: zet_regular
      fonts:
        - asset: assets/zet_regular.otf