name: abrabar
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.2+4
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter_svg: ^1.1.0
  sizer: ^2.0.15
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  bloc: ^8.0.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  gsheets: ^0.4.2
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  firebase_analytics: ^9.1.10
  flutter_local_notifications: ^9.7.0
  flutter_branch_sdk: ^6.0.0
  in_app_purchase: ^3.0.6
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/icon2.png'

flutter:
  generate: true
  assets:
        - assets/
        - assets/images/parts/
        - assets/images/test/
        - assets/images/system/
        - assets/images/previews/ru/
        - assets/images/previews/eng/
        - assets/images/category_pic/
        - assets/images/ingredients/glass/
        - assets/images/ingredients/
  uses-material-design: true
  fonts: 
    - family: zet_regular
      fonts:
        - asset: assets/fonts/zet_regular.otf
    - family: zet_expanded
      fonts:
        - asset: assets/fonts/zet_expanded.otf
    - family: zet_light
      fonts:
        - asset: assets/fonts/zet_light.otf